[package]
name = "srcrs"
version = "0.1.0"
edition = "2021"

[dependencies]
bumpalo = { version = "3.12.0", features = ["collections"] }
crc32fast = "1.3.2"
ouroboros = "0.15.5"
zerocopy = "0.6.1"

[build-dependencies]
fs_extra = "1.3.0"
